import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';

import theme from '../theme';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: {
    default: "Home",
    template: "%s | Khaled Demo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
